### ISSUE TITLE
Unexpected output in type and content

### ISSUE THREAD

**Issue by idan0610** [dlshriver/vnnlib#2]
When using vnnlib.compat.read_vnnlib_simple() with an input file whose content is (the test_nano.vnnlib file from the VNN-COMP 'test' benchmark):

```
(declare-const X_0 Real)
(declare-const Y_0 Real)

(assert (>= X_0 -1))
(assert (<= X_0 1))

(assert (<= Y_0 -1))
```

I get and output not matching the type stated by the documentation (a list of list of 2 lists, the first is a list of lists, and the second is a list of list of tuples, all that instead of a list of 2-tuple as stated), and also has the wrong content (the last output constraint is recognized as Y_0 <= 1 instead of Y_0 <= -1). 

Thank you in advance!

**Comment by dlshriver** [comment]
Can you provide the exact output that you get? It seems to be correct for me. The only thing that seems wrong is that it is a list of lists (of 2 items each) rather than a list of 2-tuples. I'll consider fixing the documentation on that, it was copied from the [original parser script](https://github.com/stanleybak/nnenum/blob/master/src/nnenum/vnnlib.py#L172). When I run it on that file I get `[[[[-1.0, 1.0], [-inf, inf]], [(array([[1]]), array([[-1.]]))]]]`. The output specification is `array([[1]]) * y <= array([[-1.]])`, which matches the vnnlib spec. Does the original script give a different output?

**Comment by idan0610** [comment]
The output I get is different. This is my output:

```
[[[[-1.0, 1]], [([[1]], [[1.]])]]]
```

To make sure, this is the call for vnnlib.compat.read_vnnlib_simple() I use:

```
from vnnlib.compat import read_vnnlib_simple

result = read_vnnlib_simple("vnncomp2023_benchmarks/benchmarks/test/test_nano.vnnlib", num_inputs=1, num_outputs=1)

# result == [[[[-1.0, 1]], [([[1]], [[1.]])]]]
```

I'm using version 0.0.1a2, which to my understanding is the latest. As implied by this code snippet, the vnnlib file "test_nano.vnnlib" is taken from the VNN-COMP 2023 test benchmark, and its content is as in my original post.

**Comment by dlshriver** [comment]
The latest version is on the main branch on GitHub, apparently it contains a fix that didn't make it into the latest version in PyPI. I fixed the function to match the type specified in the docstring and uploaded the latest version in the main branch to PyPI, so they should match now.

**Comment by idan0610** [comment]
Thanks, I checked with the latest version from this git repo and now it seems I get the correct output (but not exact match as the output you got):

``` [([[-1.0, 1.0]], [([[1]], [[-1.]])])] ```

The output type also seems to match the documentation as well.

**Comment by dlshriver** [comment]
My guess is that that is due to some version difference between our environments. What OS, python, and numpy versions are you using?

**Comment by idan0610** [comment]
Im using WSL with Ubuntu 22.04 LTS, Python 3.10.12 and numpy 1.24.3.

**Comment by dlshriver** [comment]
I get the same as you, I accidently set the number of inputs to 2 the first time I ran it, which is why I got the extra `[-inf, inf]` box.
